# Generated by Django 2.1.5 on 2019-02-09 06:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stack_overflow', '0003_auto_20190209_1157'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='questions',
            name='pub_date',
        ),
        migrations.AddField(
            model_name='questions',
            name='votes',
            field=models.IntegerField(default=0),
        ),
    ]
