# Generated by Django 2.1.5 on 2019-02-09 07:40

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('stack_overflow', '0005_auto_20190209_1228'),
    ]

    operations = [
        migrations.RenameField(
            model_name='questions',
            old_name='questionid',
            new_name='question_id',
        ),
        migrations.AddField(
            model_name='questions',
            name='ans',
            field=models.ManyToManyField(to='stack_overflow.Answers'),
        ),
        migrations.AlterField(
            model_name='answers',
            name='ans_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='stack_overflow.User'),
        ),
    ]
